"use client";

import { motion } from "framer-motion";
import { Zap, Users, PenTool } from "lucide-react";

const services = [
    {
        id: "ai",
        title: "AI Design Services",
        description: "Instant concepts generated by our advanced AI. Perfect for brainstorming and quick drafts.",
        icon: Zap,
        color: "text-indigo-500",
        bg: "bg-indigo-500/10",
    },
    {
        id: "hybrid",
        title: "AI + Manual Refinement",
        description: "The best of both worlds. AI speed with professional designer polish and details.",
        icon: Users,
        color: "text-purple-500",
        bg: "bg-purple-500/10",
    },
    {
        id: "custom",
        title: "Fully Custom Design",
        description: "Bespoke branding and design solutions tailored exactly to your unique requirements.",
        icon: PenTool,
        color: "text-pink-500",
        bg: "bg-pink-500/10",
    },
];

export function ServiceCards() {
    const scrollToSection = (id: string) => {
        const element = document.getElementById(id);
        if (element) {
            element.scrollIntoView({ behavior: "smooth" });
        }
    };

    return (
        <section className="py-12 container mx-auto px-4 md:px-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {services.map((service, index) => (
                    <motion.div
                        key={service.id}
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1 }}
                        onClick={() => scrollToSection(service.id)}
                        className="group cursor-pointer rounded-2xl border border-border bg-card p-8 hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
                    >
                        <div className={`h-12 w-12 rounded-xl ${service.bg} ${service.color} flex items-center justify-center mb-6`}>
                            <service.icon className="h-6 w-6" />
                        </div>
                        <h3 className="text-xl font-semibold mb-3">{service.title}</h3>
                        <p className="text-muted-foreground leading-relaxed">
                            {service.description}
                        </p>
                    </motion.div>
                ))}
            </div>
        </section>
    );
}
