"use client";

import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
    {
        q: "What is the main difference between AI and Custom design?",
        a: "AI design is instant and generated by algorithms based on your text prompts. It's great for quick inspiration. Custom design involves a professional human designer (Gurucraftpro) working strategically on your brand to ensure uniqueness and market fit.",
    },
    {
        q: "Can I upgrade from AI to Custom later?",
        a: "Absolutely! Many clients start with AI to generate ideas and then request a 'Hybrid' or 'Custom' service to refine those ideas into professional assets. We offer an upgrade path for this exact scenario.",
    },
    {
        q: "Are the designs copyright-safe?",
        a: "AI-generated images can be tricky with copyright depending on jurisdiction. However, our Custom and Hybrid services include full commercial rights and original vector files, ensuring you own your brand identity.",
    },
    {
        q: "What file formats do I get?",
        a: "AI plans typically provide high-res PNG/JPG. Custom and Hybrid plans provide editable source files (AI, EPS, SVG) along with web-ready standards.",
    },
];

export function ServiceFAQ() {
    return (
        <section className="py-24 bg-muted/30">
            <div className="container mx-auto px-4 md:px-6 max-w-3xl">
                <div className="text-center mb-12">
                    <h2 className="text-3xl font-bold mb-4">Frequently Asked Questions</h2>
                    <p className="text-muted-foreground">Common questions about our services and process.</p>
                </div>

                <Accordion type="single" collapsible className="w-full">
                    {faqs.map((faq, i) => (
                        <AccordionItem key={i} value={`item-${i}`}>
                            <AccordionTrigger className="text-left font-medium text-lg">{faq.q}</AccordionTrigger>
                            <AccordionContent className="text-muted-foreground leading-relaxed">
                                {faq.a}
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            </div>
        </section>
    );
}
